name: CI

on:
  push:
    branches:
      - main

jobs:
  check-html:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Check index.html
        working-directory: Homeworks/1-CI-CD_Pipelines
        run: test -f index.html

  check-css:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Check style.css
        working-directory: Homeworks/1-CI-CD_Pipelines
        run: test -f style.css

  check-images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Check photos directory
        working-directory: Homeworks/1-CI-CD_Pipelines
        run: test -d photos

  hello:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Homeworks/1-CI-CD_Pipelines

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Check index.html
        run: test -f index.html

      - name: Say hello
        run: echo "Hello from GitHub Actions!"

      - name: Show current directory
        run: pwd

      - name: Show files
        run: ls -la

      - name: Success
        run: echo "Website validation is successful"

      - name: Check home.html
        run: test -f home.html

      - name: Failure
        run: echo "Website validation failed"